#pragma once
// Auto-generated by FontForge script. PUA range starts at U+E000
#include "imguiex/icon.h"

// ICON_CHECK -> U+E000 (check.svg)
static auto constexpr ICON_CHECK                = ImGuiEx::icon<0xE000>;
// ICON_CIRCLE_QUESTION_MARK -> U+E001 (circle-question-mark.svg)
static auto constexpr ICON_CIRCLE_QUESTION_MARK = ImGuiEx::icon<0xE001>;
// ICON_EYE_OFF -> U+E002 (eye-off.svg)
static auto constexpr ICON_EYE_OFF              = ImGuiEx::icon<0xE002>;
// ICON_EYE -> U+E003 (eye.svg)
static auto constexpr ICON_EYE                  = ImGuiEx::icon<0xE003>;
// ICON_FILE_PLUS_CORNER -> U+E004 (file-plus-corner.svg)
static auto constexpr ICON_FILE_PLUS_CORNER     = ImGuiEx::icon<0xE004>;
// ICON_FILE -> U+E005 (file.svg)
static auto constexpr ICON_FILE                 = ImGuiEx::icon<0xE005>;
// ICON_FUNNEL_PLUS -> U+E006 (funnel-plus.svg)
static auto constexpr ICON_FUNNEL_PLUS          = ImGuiEx::icon<0xE006>;
// ICON_HEART_OFF -> U+E007 (heart-off.svg)
static auto constexpr ICON_HEART_OFF            = ImGuiEx::icon<0xE007>;
// ICON_HEART -> U+E008 (heart.svg)
static auto constexpr ICON_HEART                = ImGuiEx::icon<0xE008>;
// ICON_REFRESH_CW -> U+E009 (refresh-cw.svg)
static auto constexpr ICON_REFRESH_CW           = ImGuiEx::icon<0xE009>;
// ICON_SEARCH -> U+E00A (search.svg)
static auto constexpr ICON_SEARCH               = ImGuiEx::icon<0xE00A>;
// ICON_SETTINGS -> U+E00B (settings.svg)
static auto constexpr ICON_SETTINGS             = ImGuiEx::icon<0xE00B>;
// ICON_SHIRT -> U+E00C (shirt.svg)
static auto constexpr ICON_SHIRT                = ImGuiEx::icon<0xE00C>;
// ICON_SQUARE_PEN -> U+E00D (square-pen.svg)
static auto constexpr ICON_SQUARE_PEN           = ImGuiEx::icon<0xE00D>;
// ICON_USERS -> U+E00E (users.svg)
static auto constexpr ICON_USERS                = ImGuiEx::icon<0xE00E>;
// ICON_X -> U+E00F (x.svg)
static auto constexpr ICON_X                    = ImGuiEx::icon<0xE00F>;
