About = "关于"
Add = "添加"
Armor = "盔甲"
Enabled = "启用"
Delete = "删除"
Outfit = "服装"
Yes = "是"
No = "否"

[ToolBar]
File = "文件"
Close = "关闭"
RefreshActorsOutfit = "刷新角色服装"
Import = "从 JSON 导入"
Export = "导出到 JSON"
ShowOrHide = "显示/隐藏"
QuickSlots = "快捷槽"
QuickSlotsToolTip = "为角色添加一个法术，以便快速切换收藏的服装。"

[Panels]

[Panels.Characters]
ActiveOutfit = "当前服装"
Add = "[添加新角色]"

[Panels.Characters.AutoSwitch]
Empty = "[无自动切换]"
Title = "基于地点的自动切换"
Enable = "启用"
Location = "地点"
Policy0 = "世界"
Policy1 = "城镇"
Policy2 = "地下城"
Policy9 = "城市"
Policy3 = "世界（雪天）"
Policy4 = "城镇（雪天）"
Policy5 = "地下城（雪天）"
Policy10 = "城市（雪天）"
Policy6 = "世界（雨天）"
Policy7 = "城镇（雨天）"
Policy8 = "地下城（雨天）"
Policy11 = "城市（雨天）"
Policy12 = "战斗"

[Panels.Outfit]
Title = "你的服装"
Refresh = "刷新服装"
CreateNew = "新建服装"
CreateCopy = "创建副本"
Create = "创建"
CreateFromWorn = "从穿着的装备创建"
CreateHint = "创建新服装"
ShowFavorites = "收藏"
MarkFavorite = "登记为喜欢的"
UnmarkFavorite = "从喜欢的中移除"
Rename = "重命名"
ModList = "模组列表"
BodySlots = "插槽"
Untitled = "未命名"
NameConflict = "已存在"

[Panels.OutfitEdit]
ArmorNameFilter = "按名称筛选盔甲..."
EditingHint = "正在编辑服装"
MissingOutfitHint = "请选择一个服装进行编辑"
EmptyHint = "服装为空"
ModName = "模组名称"
Playable = "玩家可用"
ContainNoPlayable = "不含玩家可用的盔甲？"
ContainTemplate = "包含模板盔甲？"
ShowAllSlots = "显示所有插槽"
PassAllSlots = "所有插槽"
PreviewArmor = "预览盔甲"
ShowNoConflictArmors = "显示无冲突盔甲"
AddAll = "添加所有已选盔甲"
DeleteMultiple = "确定要删除以下 {} 套服装？"
DeleteMultipleAdditionalTips = "...还有 {} 套服装未显示"
DeleteOne = "确定要删除'{}'？"
Slot = "插槽"
Slot29 = "无"
Slot30 = "头部"
Slot31 = "头发，短"
Slot32 = "身体"
Slot33 = "手"
Slot34 = "前臂"
Slot35 = "项链"
Slot36 = "戒指"
Slot37 = "脚"
Slot38 = "小腿"
Slot39 = "盾牌"
Slot40 = "尾巴"
Slot41 = "头发，长"
Slot42 = "头环"
Slot43 = "耳朵"
Slot44 = "未知（通常为面部）"
Slot45 = "未知（通常为颈部）"
Slot46 = "未知（通常为胸部）"
Slot47 = "未知（通常为背部）"
Slot48 = "未知（通常为杂项）"
Slot49 = "未知（通常为骨盆外侧）"
Slot50 = "Decapitate-Head"
Slot51 = "Decapitate"
Slot52 = "未知（通常为骨盆下方）"
Slot53 = "未知（通常为右腿）"
Slot54 = "未知（通常为左腿）"
Slot55 = "未知（通常为面部 2）"
Slot56 = "未知（通常为胸部 2）"
Slot57 = "未知（通常为肩膀）"
Slot58 = "未知（通常为左臂）"
Slot59 = "未知（通常为右臂）"
Slot60 = "未知（通常为杂项 2）"
Slot61 = "FX"

[Panels.OutfitEdit.ConflictSolution]
Skip = "跳过"
SkipAll = "全部跳过"
Overwrite = "覆盖"
OverwriteAll = "全部覆盖"

[Panels.OutfitEdit.SlotPolicy]
Name = "插槽应用规则"
Inherit = "使用基础应用规则"
RequireEquipped = "需要穿着该插槽的装备"
AlwaysUseOutfit = "总是显示服装"
Passthrough = "允许显示未分配的插槽"
Unknown = "缺少应用规则"
InheritTooltip = "使用基础应用规则"
RequireEquippedTooltip = "服装中的装备只有在实际穿上对应插槽的装备时才显示"
AlwaysUseOutfitTooltip = "服装中分配的插槽总是显示"
PassthroughTooltip = "若仅有装备则显示装备；若插槽未分配则显示实际穿着的装备"
UnknownTooltip = "缺少应用规则"
HelpText1 = "插槽应用规则决定了每个插槽所显示的内容。存在一个适用于所有插槽的基础规则，但你可以为任意插槽单独覆盖该规则。\n\n规则说明如下：\n\n - 总是显示服装：服装中分配的插槽总是被显示出来。如果插槽什么都没被分配，那么它将什么都不显示。"
HelpText2 = "- 需要穿着该插槽的装备：服装中的装备只有在实际穿上对应插槽的装备时才会被显示。如果插槽什么装备都没有被分配，那么它将什么都不显示。\n\n - 允许显示未分配的插槽：服装中分配的插槽会显示，但只有实际在这个插槽穿上装备时才有效。如果插槽没有被分配，则会显示实际该插槽穿着的装备（如有）。"
HelpText3 = "注意：由于有些装备会占用多个插槽，所以有可能就某个插槽应该显示的内容得出相互矛盾的结果。在这种情况下，系统将从中任选其一。"

[Panels.OutfitEdit.ArmorSource]
ByFormID = "按 FormID"
NearObjectInventory = "附近物体的物品栏"
NearNpcCarried = "附近 NPC 携带"
AllArmors = "所有盔甲"
