About = "About"
Add = "Add"
Armor = "Armor"
Enabled = "Enabled"
Delete = "Delete"
Outfit = "Outfit"
EditOutfit = "Edit Outfit"
CharacterEditPanel = "Character Edit Panel"
EditingActor = "Editing Actor"
Characters = "Characters"
Yes = "Yes"
No = "No"

[ToolBar]
File = "File"
Close = "Close"
Settings = "Settings"
RefreshPlayerArmor = "Refresh Player Armor"
Import = "Import from JSON"
Export = "Export to JSON"
ShowOrHide = "Show/Hide"
Quickslots = "Quickslots"
QuickslotsToolTip = "Adds a spell to your character, to allow quick switching between favorited outfits."

[Panels]

[Panels.Outfit]
Title = "Your Outfits"
Refresh = "Refresh Outfits"
Create = "Create"
CreateFromWorn = "Create From Worn"
CreateHint = "Create a new outfit"
Filter = "Filter Outfit"
ShowFavorites = "Show Favorites"
MarkFavorite = "Mark Favorite"
UnmarkFavorite = "Unmark Favorite"
Rename = "Rename"
Delete = "Delete"
Enable = "Enable"
Disable = "Disable"
MissingActorHint = "Please selec an actor to edit"
ModList = "Mod List"
BodySlots = "Body Slots"

[Panels.OutfitEdit]
Title = "Outfit Edit Panel"
EditingHint = "Editing Outfit"
MissingOutfitHint = "Please selec an outfit to edit"
EmptyHint = "Outfit is empty"
ModName = "Mod Name"
Playable = "Playable"
Template = "Template Armor"
Filterers = "Filterers"
ShowAllSlots = "Show All Body Slots"
AddAll = "Add All Selected Armors"
RemoveArmor = "Remove Armor"
ConfirmRemoveConfictArmors = "This armor conflicts with some of the armor already in the outfit.\n\nWould you like to remove the conflicting pieces, and add this piece?"
Delete = "Delete outfit"
Slot = "Slot"
SlotPolicies = "Slot Policies"
SlotPolicyHelp = "Slot Policy Help"
SlotPolicyHelpText1 = "The Slot Policy determines what is shown in each slot. There is a base policy which applies to all slots, but you can override the policy for any slot.\n\nThe policies are:\n\n - Always use outfit: The item assigned in the outfit is always shown. If the slot is unassigned, then it is always left empty."
SlotPolicyHelpText2 = "- Require equipped: The item assigned in the outfit is shown, but only if you actually have an item equipped in that slot. If the slot is unassigned, then it is always left empty.\n\n - Passthrough: The item assigned in the outfit is shown, but only if you actually have an item equipped in that slot. If the slot is unassigned, then it will show the real armor you have equipped, if any."
SlotPolicyHelpText3 = "Note that, because some armor pieces occupy multiple slots, it is possible to arrive at contradictory answer for what should be shown in a given slot. In that case, we will just pick one of the answers."
Slot29 = "None"
Slot30 = "Head"
Slot31 = "Hair, Short"
Slot32 = "Body"
Slot33 = "Hands"
Slot34 = "Forearms"
Slot35 = "Amulet"
Slot36 = "Ring"
Slot37 = "Feet"
Slot38 = "Calves"
Slot39 = "Shield"
Slot40 = "Tail"
Slot41 = "Hair, Long"
Slot42 = "Circlet"
Slot43 = "Ears"
Slot44 = "Unofficial (Typically Face)"
Slot45 = "Unofficial (Typically Neck)"
Slot46 = "Unofficial (Typically Chest)"
Slot47 = "Unofficial (Typically Back)"
Slot48 = "Unofficial (Typically Misc)"
Slot49 = "Unofficial (Typically Pelvis Outer)"
Slot50 = "Decapitate-Head"
Slot51 = "Decapitate"
Slot52 = "Unofficial (Typically Pelvis Under)"
Slot53 = "Unofficial (Typically Right Leg)"
Slot54 = "Unofficial (Typically Left Leg)"
Slot55 = "Unofficial (Typically Face 2)"
Slot56 = "Unofficial (Typically Chest 2)"
Slot57 = "Unofficial (Typically Shoulders)"
Slot58 = "Unofficial (Typically Left Arm)"
Slot59 = "Unofficial (Typically Right Arm)"
Slot60 = "Unofficial (Typically Misc 2)"
Slot61 = "FX"
[Panels.OutfitEdit.ArmomrGenerator]
Title = "Armor Generator"
ByFormID = "By FormID"
NearObjectInventory = "Near Object Inventory"
NearObjects = "Near Objects"
NearNpcCarried = "Near NPC carried"
AllArmors = "All Armors"
