About = "About"
Add = "Add"
Armor = "Armor"
Enabled = "Enabled"
Delete = "Delete"
Outfit = "Outfit"
EditOutfit = "Edit Outfit"
CharacterEditPanel = "Character Edit Panel"
EditingActor = "Editing Actor"
Characters = "Characters"
Yes = "Yes"
No = "No"

[ToolBar]
File = "File"
Close = "Close"
Settings = "Settings"
RefreshActorsOutfit = "Refresh Actors Outfit"
Import = "Import from JSON"
Export = "Export to JSON"
ShowOrHide = "Show/Hide"
QuickSlots = "QuickSlots"
QuickSlotsToolTip = "Adds a spell to your character, to allow quick switching between favorited outfits."

[Panels]

[Panels.Characters]
Title = "Characters Edit Panel"
Refresh = "Refresh Characters"
ActiveOutfit = "Active Outfit"
Add = "[Add New Character]"

[Panels.Characters.AutoSwitch]
Empty = "[No Autoswitch]"
Title = "Location-Based Autoswitch"
Enable = "Enable"
Location = "Location"
Policy0 = "World"
Policy1 = "Towns"
Policy2 = "Dungeons"
Policy9 = "City"
Policy3 = "World (Snowy)"
Policy4 = "Towns (Snowy)"
Policy5 = "Dungeons (Snowy)"
Policy10 = "City (Snowy)"
Policy6 = "World (Rainy)"
Policy7 = "Towns (Rainy)"
Policy8 = "Dungeons (Rainy)"
Policy11 = "City (Rainy)"
Policy12 = "Combat"

[Panels.Outfit]
Title = "Your Outfits"
Refresh = "Refresh Outfits"
CreateNew = "Create New outfit"
CreateCopy = "Create Copy"
Create = "Create"
CreateFromWorn = "Create From Worn"
CreateHint = "Create a new outfit"
Filter = "Filter Outfit"
ShowFavorites = "Favorites"
MarkFavorite = "Mark Favorite"
UnmarkFavorite = "Unmark Favorite"
Rename = "Rename"
Delete = "Delete"
Enable = "Enable"
Disable = "Disable"
MissingActorHint = "Please selec an actor to edit"
ModList = "Mod List"
BodySlots = "Body Slots"
Untitled = "Untitled"
NameConflict = "alreay exists"

[Panels.OutfitEdit]
EditingHint = "Editing Outfit"
MissingOutfitHint = "Please selec an outfit to edit"
EmptyHint = "Outfit is empty"
ModName = "Mod Name"
Playable = "Playable"
Template = "Template Armor"
ContainNoPlayable = "Contain no playable armors?"
ContainTemplate = "Contain template armors?"
Filterers = "Filterers"
ShowAllSlots = "Show All Body Slots"
PassAllSlots = "All Slots"
PreviewArmor = "Preview Armor"
ShowNoConflictArmors = "Show no conflict armos"
AddAll = "Add All Selected Armors"
RemoveArmor = "Remove Armor"
ConfirmRemoveConflictArmors = "This armor conflicts with some of the armor already in the outfit.\n\nWould you like to remove the conflicting pieces, and add this piece?"
DeleteMultiple = "Are you sure you want to delete the following {} outfits?"
DeleteMultipleAdditionalTips = "...{} additional outfits not shown"
DeleteOne = "Are you sure you want to delete '{}'?"
Slot = "Slot"
Slot29 = "None"
Slot30 = "Head"
Slot31 = "Hair, Short"
Slot32 = "Body"
Slot33 = "Hands"
Slot34 = "Forearms"
Slot35 = "Amulet"
Slot36 = "Ring"
Slot37 = "Feet"
Slot38 = "Calves"
Slot39 = "Shield"
Slot40 = "Tail"
Slot41 = "Hair, Long"
Slot42 = "Circlet"
Slot43 = "Ears"
Slot44 = "Unofficial (Typically Face)"
Slot45 = "Unofficial (Typically Neck)"
Slot46 = "Unofficial (Typically Chest)"
Slot47 = "Unofficial (Typically Back)"
Slot48 = "Unofficial (Typically Misc)"
Slot49 = "Unofficial (Typically Pelvis Outer)"
Slot50 = "Decapitate-Head"
Slot51 = "Decapitate"
Slot52 = "Unofficial (Typically Pelvis Under)"
Slot53 = "Unofficial (Typically Right Leg)"
Slot54 = "Unofficial (Typically Left Leg)"
Slot55 = "Unofficial (Typically Face 2)"
Slot56 = "Unofficial (Typically Chest 2)"
Slot57 = "Unofficial (Typically Shoulders)"
Slot58 = "Unofficial (Typically Left Arm)"
Slot59 = "Unofficial (Typically Right Arm)"
Slot60 = "Unofficial (Typically Misc 2)"
Slot61 = "FX"
[Panels.OutfitEdit.ConflictSolution]
Skip = "Skip"
SkipAll = "Skip All"
Overwrite = "Overwrite"
OverwriteAll = "Overwrite All"

[Panels.OutfitEdit.SlotPolicy]
Name = "Slot Policies"
Inherit = "Use base policy"
RequireEquipped = "Require equipped"
AlwaysUseOutfit = "Always use outfit"
Passthrough = "Passthrough"
Unknown = "Missing Policy"
InheritTooltip = "Use base policy"
RequireEquippedTooltip = "If outfit and equipped, show outfit"
AlwaysUseOutfitTooltip = "If outfit, show outfit"
PassthroughTooltip = "If only equipped, show equipped. If both, show outfit"
UnknownTooltip = "Missing Policy"
Help = "Slot Policy Help"
HelpText1 = "The Slot Policy determines what is shown in each slot. There is a base policy which applies to all slots, but you can override the policy for any slot.\n\nThe policies are:\n\n - Always use outfit: The item assigned in the outfit is always shown. If the slot is unassigned, then it is always left empty."
HelpText2 = "- Require equipped: The item assigned in the outfit is shown, but only if you actually have an item equipped in that slot. If the slot is unassigned, then it is always left empty.\n\n - Passthrough: The item assigned in the outfit is shown, but only if you actually have an item equipped in that slot. If the slot is unassigned, then it will show the real armor you have equipped, if any."
HelpText3 = "Note that, because some armor pieces occupy multiple slots, it is possible to arrive at contradictory answer for what should be shown in a given slot. In that case, we will just pick one of the answers."

[Panels.OutfitEdit.ArmorSource]
Title = "Armor Generator"
ByFormID = "By FormID"
NearObjectInventory = "Near Object Inventory"
NearObjects = "Near Objects"
NearNpcCarried = "Near NPC carried"
AllArmors = "All Armors"
