# SosGui settings file

[UiSetting]
# auto save when change font in UI
selectedThemeIndex = 41       # int32, allow negative value
globalFontScale = 1.000000    # float

[UiSetting.FontInfo]
filePath = ""       # std::string
familyNam = ""      # std::string
familyIndex = -1    # int32_t
fontIndex = 1       # int32_t
faceIndex = 1       # uint32_t disallow negative value
bold = true         # bool
oblique = false     # bool