#debug = false
#language = "english"
### Shortcut: <key> or <modifier> + <key>
### e.g. f1, ctrl+f1, ctrl+shift+f1
### Case and spaces are ignored.
### 1. Cannot use a modifier key alone
### 2. Cannot end with a modifier key
### 3. Cannot combine multiple regular keys (e.g. A + B).
### Invalid shortcuts will be ignored and fall back to the default: ctrl+o
###
### Modifier keys : ctrl, shift, alt
### Letters       : a - z
### Number row    : num0 - num9
### Function keys : f1 - f12
### Navigation    : home, end, pageup, pagedown, up, down, left, right, insert, delete
### Numpad        : kp_0 - kp_9, kp_multiply, kp_plus, kp_subtract, kp_decimal, kp_divide, kp_enter
### System        : escape, backspace, tab, enter, spacebar, capslock, numlock, scrolllock, pause, printscreen
### Punctuation   : minus, equals, bracketleft, bracketright, backslash, semicolon, apostrophe, tilde, comma, period, slash
#shortcut = "ctrl+o"
